"bug":
  any:
    title:
      - "(?i)^\\[?bug\\]?"
      - "(?i)crash"
    body:
      - "(?i)stack trace"
      - "(?i)error"

"feature":
  any:
    title:
      - "(?i)^\\[?feature\\]?"
      - "(?i)new feature"
    body:
      - "(?i)enhancement"
      - "(?i)improvement"

"documentation":
  any:
    title:
      - "(?i)docs?"
    body:
      - "(?i)readme"
      - "(?i)documentation"

"priority: high":
  any:
    body:
      - "(?i)critical"
      - "(?i)urgent"

"status: needs triage":
  any:
    body:
      - ".*"   # default fallback label for uncategorized issues
