# CodeGuardian Configuration - Fixed Structure

[output]
directory = "reports"
format = "json"

[security]
enabled = true

[git]
conventional_commits = true
commit_template = "{type}({scope}): {description}"
require_signed_commits = false

[performance]
enabled = true
check_allocations = true
check_async_blocking = true
max_complexity = 15
max_function_length = 150
enable_profiling = false
max_memory_usage_mb = 512
max_cpu_usage_percent = 80

[analyzers]
[analyzers.broken_files]
enabled = false
detect_merge_conflicts = false
detect_ai_placeholders = false
detect_duplicates = false

[analyzers.broken_files.conflicts]
fail_on_conflicts = false

[files]
include_patterns = []
exclude_patterns = ["*.log", "*.tmp", "target/", "node_modules/", ".git/"]
analyze_extensions = [".rs", ".js", ".ts", ".py", ".java"]
skip_binaries = true
max_file_size_bytes = 10485760
skip_large_files = true

[severity]
custom_levels = ["info", "low", "medium", "high", "critical"]
enable_escalation = true
escalation_threshold = 5

[integrations]
[integrations.github]
enabled = false
repository = ""
token = ""
create_issues = false
issue_labels = ["security", "codeguardian"]
comment_prs = false
min_severity = "high"

[integrations.gitlab]
enabled = false
project = ""
token = ""
create_issues = false
issue_labels = ["security", "codeguardian"]
comment_mrs = false
min_severity = "high"

[analysis]
enabled = true
analyze_binaries = false
timeout_seconds = 300
parallel_processing = true
max_workers = 4
enable_caching = true
cache_dir = ".codeguardian/cache"
cache_expiration_days = 7

[optimization]
enable_optimized_analyzers = true
enable_file_caching = true
max_parallel_workers = 4
max_memory_file_size = 10485760
streaming_chunk_size = 65536
max_findings_per_file = 50
pattern_cache_size = 1000

[optimization.cache_cleanup]
enabled = true
max_age_days = 7
max_size_mb = 100
cleanup_frequency = 10

[optimization.early_termination]
enabled = true
max_analysis_time_seconds = 30
max_lines_per_file = 10000
skip_large_files_bytes = 52428800
