[general]
max_file_size = 5242880
max_memory_mb = 256
parallel_workers = 2
timeout_seconds = 120
exclude_patterns = [
    "target/**",
    ".git/**",
]
include_patterns = ["**/*.rs"]

[integrity]
enabled = true
algorithm = "Blake3"
baseline_file = ".codeguardian/integrity.baseline"
auto_update_baseline = false
check_permissions = false

[lint_drift]
enabled = false
config_files = ["Cargo.toml"]
baseline_file = ".codeguardian/lint_drift.baseline"
auto_update_baseline = false
strict_mode = false

[non_production]
enabled = true
exclude_test_files = true
exclude_example_files = true

[[non_production.patterns]]
pattern = '(?i)\b(todo|fixme|hack|xxx)\b'
description = "Non-production code markers"
severity = "medium"

[dependency]
enabled = true
check_outdated = true
check_vulnerabilities = true
check_unused = true
check_duplicates = true
max_age_days = 365
vulnerability_threshold = "medium"

[performance_analyzer]
enabled = true
check_nested_loops = true
check_string_operations = true
check_blocking_io = true
max_complexity = 10
max_function_length = 50

[security_analyzer]
enabled = true
check_sql_injection = true
check_xss = true
check_command_injection = true
check_hardcoded_secrets = true
min_entropy_threshold = 3.5

[code_quality]
enabled = true
check_magic_numbers = true
check_complex_conditions = true
check_deep_nesting = true
check_commented_code = true
max_nesting_depth = 6
max_file_size = 500

[security]
enabled = true
check_secrets = true
check_unsafe_code = true
check_dependencies = true
secret_patterns = [
    '''(?i)(password|passwd|pwd)\s*[:=]\s*['\x22][^'\x22]{8,}['\x22]''',
    '''(?i)(api[_-]?key|apikey)\s*[:=]\s*['\x22][^'\x22]{16,}['\x22]''',
    '''(?i)(secret|token)\s*[:=]\s*['\x22][^'\x22]{16,}['\x22]''',
]
entropy_threshold = 4.5

[performance]
enabled = false
check_allocations = false
check_async_blocking = false
max_complexity = 15
max_function_length = 150

[optimization]
enable_optimized_analyzers = true
enable_file_caching = true
max_parallel_workers = 2
max_memory_file_size = 10485760
streaming_chunk_size = 65536
max_findings_per_file = 50
pattern_cache_size = 1000

[optimization.cache_cleanup]
enabled = true
max_age_days = 7
max_size_mb = 100
cleanup_frequency = 10

[optimization.early_termination]
enabled = true
max_analysis_time_seconds = 30
max_lines_per_file = 10000
skip_large_files_bytes = 52428800
