name: CodeGuardian CI (Improved)

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * 1'  # Weekly full scan

# Prevent concurrent runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeguardian-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
        contents: read
        issues: write
        pull-requests: write

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Need full history for diff

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: true

    - name: Clean stale locks
      run: |
          rm -f target/debug/.cargo-lock target/release/.cargo-lock

    - name: Build CodeGuardian
      run: |
          cargo build --release --quiet

    - name: Run CodeGuardian (PR diff-only)
      run: |
        # Diff-only mode for PRs - fast and focused feedback
        mkdir -p build/analysis-results
        ./target/release/do-codeguardian check . \
          --diff origin/main..HEAD \
          --format json \
          --out build/analysis-results/results.json \
          --emit-md build/analysis-results/report.md

        echo "CodeGuardian analysis completed. Results saved to build/analysis-results/results.json"

    - name: Prevent duplicate GitHub issues
      if: github.event_name == 'pull_request'
      run: |
        # Load enhanced duplicate prevention utilities
        source ./scripts/github-issue-utils.sh

        # Generate unique issue title with PR context
        ISSUE_TITLE="CodeGuardian PR Analysis - PR #${{ github.event.number }}"

        # Check for existing issues before creating
        COMMIT_HASH=$(git rev-parse --short HEAD)

        # Use enhanced duplicate detection with ML and semantic matching
        EXISTING_ISSUE=$(detect_duplicate_issue \
          "${{ github.repository }}" \
          "$ISSUE_TITLE" \
          "$(cat results.json)" \
          "$COMMIT_HASH")

        if [ -n "$EXISTING_ISSUE" ]; then
          echo "::notice::Duplicate prevented - issue already exists: #$EXISTING_ISSUE"
          echo "DUPLICATE_PREVENTED=true" >> $GITHUB_ENV
          echo "EXISTING_ISSUE=$EXISTING_ISSUE" >> $GITHUB_ENV
        else
          echo "::notice::No duplicates found - safe to create new issue"
          echo "DUPLICATE_PREVENTED=false" >> $GITHUB_ENV
        fi

    - name: Create GitHub issue for PR findings
      if: github.event_name == 'pull_request' && env.DUPLICATE_PREVENTED == 'false'
      run: |
        # Use CodeGuardian's enhanced issue creation with duplicate prevention
        ./target/release/do-codeguardian gh-issue \
          --from results.json \
          --repo "${{ github.repository }}" \
          --title "CodeGuardian PR Analysis - PR #${{ github.event.number }}" \
          --labels "codeguardian,automated,pr-${{ github.event.number }},duplicate-prevention-enabled" \
          --mode checklist \
          --summary-max-issues 15 \
          --duplicate-check \
          --ml-enhanced
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PR_NUMBER: "${{ github.event.number }}"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: codeguardian-pr-results
        path: |
          build/analysis-results/results.json
          build/analysis-results/report.md

  codeguardian-full:
    if: github.event_name == 'push' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
        contents: read
        issues: write

    steps:
    - uses: actions/checkout@v5

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: true

    - name: Clean stale locks
      run: |
          rm -f target/debug/.cargo-lock target/release/.cargo-lock

    - name: Build CodeGuardian
      run: |
          cargo build --release --quiet

    - name: Run CodeGuardian (Full scan)
      run: |
        # Full scan for main branch pushes
        mkdir -p build/analysis-results
        ./target/release/do-codeguardian check . \
          --format json \
          --out build/analysis-results/results.json \
          --emit-md build/analysis-results/report.md

        echo "CodeGuardian analysis completed. Results saved to build/analysis-results/results.json"

    - name: Prevent duplicate GitHub issues for full scan
      if: github.event_name == 'push' || github.event_name == 'schedule'
      run: |
        # Load enhanced duplicate prevention utilities
        source ./scripts/github-issue-utils.sh

        # Generate unique issue title with date and commit info
        ISSUE_TITLE="CodeGuardian Full Analysis - $(date +%Y%m%d)"
        COMMIT_HASH=$(git rev-parse --short HEAD)

        # Use enhanced duplicate detection
        EXISTING_ISSUE=$(detect_duplicate_issue \
          "${{ github.repository }}" \
          "$ISSUE_TITLE" \
          "$(cat results.json)" \
          "$COMMIT_HASH")

        if [ -n "$EXISTING_ISSUE" ]; then
          echo "::notice::Duplicate prevented - issue already exists: #$EXISTING_ISSUE"
          echo "DUPLICATE_PREVENTED=true" >> $GITHUB_ENV
          echo "EXISTING_ISSUE=$EXISTING_ISSUE" >> $GITHUB_ENV
        else
          echo "::notice::No duplicates found - safe to create new issue"
          echo "DUPLICATE_PREVENTED=false" >> $GITHUB_ENV
        fi

    - name: Create GitHub issue for full scan findings
      if: (github.event_name == 'push' || github.event_name == 'schedule') && env.DUPLICATE_PREVENTED == 'false'
      run: |
        # Use CodeGuardian's enhanced issue creation
        ./target/release/do-codeguardian gh-issue \
          --from results.json \
          --repo "${{ github.repository }}" \
          --title "CodeGuardian Full Analysis - $(date +%Y%m%d)" \
          --labels "codeguardian,automated,full-scan,duplicate-prevention-enabled" \
          --mode checklist \
          --summary-max-issues 20 \
          --duplicate-check \
          --ml-enhanced
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: codeguardian-full-results
        path: |
          build/analysis-results/results.json
          build/analysis-results/report.md

  codeguardian-baseline:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
        contents: write

    steps:
    - uses: actions/checkout@v5

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: true

    - name: Clean stale locks
      run: |
          rm -f target/debug/.cargo-lock target/release/.cargo-lock

    - name: Build CodeGuardian
      run: |
          cargo build --release --quiet

    - name: Update baseline
      run: |
        set -e  # Exit on any error

        # Run CodeGuardian to generate baseline
        mkdir -p build/analysis-results
        ./target/release/do-codeguardian check . \
          --format json \
          --out build/analysis-results/baseline.json

        # Check if build/analysis-results/baseline.json exists and has changes
        if git ls-files --error-unmatch build/analysis-results/baseline.json >/dev/null 2>&1; then
          # File is tracked, check for changes
          if ! git diff --quiet build/analysis-results/baseline.json; then
           echo "Baseline has changes, committing..."
           git config user.name "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git add build/analysis-results/baseline.json
           git commit -m "chore: update CodeGuardian baseline [skip ci]"
           # Retry push up to 3 times in case of conflicts
           for i in {1..3}; do
             if git push; then
               echo "Baseline updated successfully"
               break
             else
               echo "Push failed (attempt $i), retrying..."
               git pull --rebase
             fi
           done
          else
           echo "No changes to baseline"
          fi
        else
          # File not tracked, add it
          echo "Adding new baseline file"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add build/analysis-results/baseline.json
          git commit -m "chore: add initial CodeGuardian baseline [skip ci]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
